export const prefix = 'sacolaPedidos';

export const ENVIA_PARA_VARIAVELCONTEXTOGERAL = `ENVIA_PARA_VARIAVELCONTEXTOGERAL`;
export const ENVIA_PARA_SACOLA = `ENVIA_PARA_SACOLA`;
export const REMOVERA_PEDIDO_SACOLA = `REMOVERA_PEDIDO_SACOLA`;
export const ENVIARA_PEDIDOS_DA_SACOLA = `ENVIARA_PEDIDOS_DA_SACOLA`;

